name: Ruby Gem

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Set up Ruby 3.4.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
      - name: Build
        run: |
          bundle install
          bundle exec rake gem
          
          mkdir -p ~/.gem
          cat <<AAA > ~/.gem/.mirrorrc
          ---
          - from: https://repy.github.io/hidaping
            to: /home/runner/gemrepos
          AAA
          mkdir -p /home/runner/gemrepos/gems
          gem install rubygems-mirror
          gem mirror
          
          cp ./pkg/hidaping-*.gem /home/runner/gemrepos/gems/
          cd /home/runner/gemrepos
          gem generate_index
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: /home/runner/gemrepos
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
